# Generated by Django 4.2 on 2023-05-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_customer', models.CharField(blank=True, max_length=100, null=True)),
                ('key_source', models.CharField(blank=True, max_length=100, null=True)),
                ('key_value', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
