# Generated by Django 4.2 on 2023-05-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerkeys',
            old_name='key_customer',
            new_name='google_docs',
        ),
        migrations.RenameField(
            model_name='customerkeys',
            old_name='key_source',
            new_name='sfkb_password',
        ),
        migrations.RenameField(
            model_name='customerkeys',
            old_name='key_value',
            new_name='sfkb_user_name',
        ),
        migrations.AddField(
            model_name='customerkeys',
            name='customer_name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
